### ISSUE TITLE
Completely breaks on android, even with proposed fixes in other threads

### ISSUE THREAD

**Issue by mwawrusch** [deepak786/intercom_flutter#105]
I tried various approaches as outlined but still get this:

```
Launching lib/main.dart on moto g 7 power in debug mode...
package:roji_wallet/main.dart:1
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
W/ConnectionTracker(19630): Exception thrown while unbinding
W/ConnectionTracker(19630): java.lang.IllegalArgumentException: Service not registered: lp@71ca7e8
W/ConnectionTracker(19630): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1571)
W/ConnectionTracker(19630): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1707)
W/ConnectionTracker(19630): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:717)
W/ConnectionTracker(19630): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204217066@20.42.17 (100406-0):1)
W/ConnectionTracker(19630): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204217066@20.42.17 (100406-0):2)
W/ConnectionTracker(19630): 	at lq.D(:com.google.android.gms.dynamite_measurementdynamite@204217066@20.42.17 (100406-0):10)
W/ConnectionTracker(19630): 	at lc.a(:com.google.android.gms.dynamite_measurementdynamite@204217066@20.42.17 (100406-0):2)
W/ConnectionTracker(19630): 	at ee.run(:com.google.android.gms.dynamite_measurementdynamite@204217066@20.42.17 (100406-0):3)
W/ConnectionTracker(19630): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
W/ConnectionTracker(19630): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(19630): 	at ix.run(:com.google.android.gms.dynamite_measurementdynamite@204217066@20.42.17 (100406-0):6)
Connecting to VM Service at ws://127.0.0.1:56459/UKFeJZkLvmk=/ws
E/flutter (19630): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel maido.io/intercom)
E/flutter (19630): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:157
E/flutter (19630): <asynchronous suspension>
E/flutter (19630): #1      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
E/flutter (19630): #2      Intercom.initialize
package:intercom_flutter/intercom_flutter.dart:20
E/flutter (19630): #3      main
package:roji_wallet/main.dart:15
E/flutter (19630): <asynchronous suspension>
E/flutter (19630): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (19630): #5      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (19630): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (19630): #7      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (19630): #8      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (19630): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (19630): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (19630): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

my flutter doctor

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)
```

**Comment by Zazo032** [comment]
Try the following set of commands:

1. `flutter clean`
2. `flutter pub cache repair`
3. `flutter pub get`

And see if that fixes the issue

**Comment by henlamk** [comment]
I am getting the same issue, but not while developing the app. 
Strangely, this only happens with the published version that's on the play store.
