### ISSUE TITLE
[iOS] MissingPluginException(No implementation found for method isIntercomPush on channel maido.io/intercom)

### ISSUE THREAD

**Issue by ferrarafer** [deepak786/intercom_flutter#134]
I get an exception when trying to identify if the push notification is from Intercom or FCM.

NSPhotoLibraryUsageDescription on Info.plist
```
<key>NSPhotoLibraryUsageDescription</key>
<string>It is required for customer support and chat</string>

```
**System Specs**
```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H524 darwin-x64, locale es-419)
    • Flutter version 2.0.3 at /Users/Fermento/.asdf/installs/flutter/2.0.3-stable
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 10 (API 29) (emulator)
    • iPhone 12 Pro (mobile)             • F9190B7A-EA2D-4BC5-8CB2-11FE724EB8B5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • Mac OS X 10.15.7 19H524 darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

**Exception**
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method isIntercomPush on channel maido.io/intercom)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      Intercom.isIntercomPush (package:intercom_flutter/intercom_flutter.dart:161:20)
<asynchronous suspension>
```

**Comment by deepak786** [comment]
This method has not implemented yet in the iOS method channel. I think there is no equivalent method in iOS.
Intercom uses APNS for push notifications in iOS and it internally handles everything. But for Android, uses FCM, and there we need to check externally about the Intercom push.

If you know what would be the alternative to this method in IOS then please let us know.
