### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by safield** [deepak786/intercom_flutter#167]
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (9 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

This issue occurs with example code given in the repo readme. Specifically...

```
import 'package:intercom_flutter/intercom_flutter.dart';

void main() async {
    await Intercom.initialize('appIdHere', iosApiKey: 'iosKeyHere', androidApiKey: 'androidKeyHere');
    runApp(App());
}

class App extends StatelessWidget {

    @override
    Widget build(BuildContext context) {
        return FlatButton(
            child: Text('Open Intercom'),
            onPressed: () async {
                await Intercom.displayMessenger();
            },
        );
    }
}
```

```
E/flutter ( 5212): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 5212): #0      MethodChannel.binaryMessenger
package:flutter/…/services/platform_channel.dart:142
E/flutter ( 5212): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:148
E/flutter ( 5212): #2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:331
E/flutter ( 5212): #3      MethodChannelIntercomFlutter.initialize
package:intercom_flutter_platform_interface/method_channel_intercom_flutter.dart:15
E/flutter ( 5212): #4      Intercom.initialize
package:intercom_flutter/intercom_flutter.dart:18
E/flutter ( 5212): #5      main
package:intercom_test/main.dart:5
E/flutter ( 5212): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter ( 5212): #7      _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 5212): #8      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 5212): #9      _runZoned (dart:async/zone.dart:1789:10)
E/flutter ( 5212): #10     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter ( 5212): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter ( 5212): #12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 5212): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by jsgalarraga** [comment]
Same issue here, any solution?

**Comment by deepak786** [comment]
@jsgalarraga @safield could you please provide the reproducible sample?

**Comment by jsgalarraga** [comment]
@deepak786 
Sure, I created a new Flutter project with `flutter create intercom_demo` and replaced all `main.dart` file with code below.

flutter version: 2.2.3 (but also tested with 2.5.3)
intercom_flutter plugin version: 5.0.3


```
import 'package:flutter/material.dart';
import 'package:intercom_flutter/intercom_flutter.dart';

void main() async {
  await Intercom.initialize('appIdHere',
      iosApiKey: 'iosKeyHere', androidApiKey: 'androidKeyHere');
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Intercom Demo App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Intercom Demo App'),
        ),
        body: Center(
          child: TextButton(
            child: const Text('Open Intercom'),
            onPressed: () async {
              await Intercom.displayMessenger();
            },
          ),
        ),
      ),
    );
  }
}
```

**Comment by jsgalarraga** [comment]
Already found a solution.
just add `WidgetsFlutterBinding.ensureInitialized();` before `await Intercom.initialize('appIdHere', iosApiKey: 'iosKeyHere', androidApiKey: 'androidKeyHere');` on `main.dart`
Should be changed on the docs

**Comment by deepak786** [comment]
@jsgalarraga glad to know that you found the solution. I will update the docs.
Thanks
