### ISSUE TITLE
Android: missing dependencies

### ISSUE THREAD

**Issue by kmckinley** [deepak786/intercom_flutter#17]
I'm running into the below error with Android.  I was able to fix this by adding 'compile 'io.intercom.android:intercom-sdk-base:5.+' to the dependencies of the app build.gradle file.  

I'm not sure if it's possible to have this automatically added, but if not could we add it to the doc's to add?

```
E/flutter (31448): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
E/flutter (31448): 	at io.intercom.android.sdk.identity.AppConfig.<init>(AppConfig.java:102)
E/flutter (31448): 	at io.intercom.android.sdk.Injector.initWithAppCredentials(Injector.java:100)
E/flutter (31448): 	at io.intercom.android.sdk.RealIntercom.create(RealIntercom.java:72)
E/flutter (31448): 	at io.intercom.android.sdk.Intercom.initialize(Intercom.java:68)
E/flutter (31448): 	at io.maido.intercom.IntercomFlutterPlugin.onMethodCall(IntercomFlutterPlugin.kt:28)
E/flutter (31448): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/flutter (31448): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/flutter (31448): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/flutter (31448): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (31448): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (31448): 	at android.os.Looper.loop(Looper.java:160)
E/flutter (31448): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/flutter (31448): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (31448): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (31448): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (31448): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/data/app/com.xylem.gpda_lite-_Gdlk60K94VE6qTrgzM50w==/base.apk"],nativeLibraryDirectories=[/data/app/com.xylem.gpda_lite-_Gdlk60K94VE6qTrgzM50w==/lib/arm64, /data/app/com.xylem.gpda_lite-_Gdlk60K94VE6qTrgzM50w==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/flutter (31448): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/flutter (31448): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/flutter (31448): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (31448): 	... 15 more
E/flutter (31448): 
F/flutter (31448): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
```

**Comment by Zazo032** [comment]
Which Flutter version are you using? And which version of the plugin?

**Comment by kmckinley** [comment]
Flutter version: v1.5.4-hotfix.2
Plugin version: 2.0.2

**Comment by Zazo032** [comment]
I created a new project in both stable and master and didn't come up with that error when running on Android emulator and physical device. As no one else has reported this issue, if you or someone else comes across this again, please, open a new issue.

**Comment by Spikes042** [comment]
If I may add, intercom-sdk-base dependency and all implementation dependencies (AFAIK) are supposed to be handled by the actual plugin, not your app. If you encountered such issue then there must be a problem with your setup/environment.
I've had this before with some of the firebase plugins and couldn't figure out exactly why or even how I fixed it.
Nevertheless, always run `flutter clean` as it fixes a lot of issues with packages.
