### ISSUE TITLE
Android Application class not being able to build

### ISSUE THREAD

**Issue by vlazdra** [deepak786/intercom_flutter#315]
Hi! 👋 
As per the the Changelog, we now need to add the Intercom initialization to the Android Application class.
But when I do so, the project won't build properly. Any ideas as to why?

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
main.dart:1
e: file:///Users/vlazdra/Documents/Projects/project/android/app/src/main/kotlin/com/project/app/ProjectApplication.kt:4:26 Unresolved reference: IntercomFlutterPlugin
e: file:///Users/vlazdra/Documents/Projects/project/android/app/src/main/kotlin/com/project/app/ProjectApplication.kt:14:13 Unresolved reference: IntercomFlutterPlugin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevelopmentDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Exception: Gradle task assembleDevelopmentDebug failed with exit code 1
Exited
```

The setup of the Application class
```
package com.project.app

import io.flutter.app.FlutterApplication
import io.maido.intercom.IntercomFlutterPlugin

class ProjectApplication: FlutterApplication() {
    override fun onCreate() {
        super.onCreate()

            IntercomFlutterPlugin.initSdk(
                this,
                appId = "intercomKey",
                androidApiKey = "intercomAndroidKey"
            )
    }
}
```

**Comment by Zazo032** [comment]
Looks like it can't find the `IntercomFlutterPlugin` reference - can you try running `flutter clean` and `flutter pub cache clean` and try again? Which Flutter version and which plugin version are you using?

**Comment by vlazdra** [comment]
That's strange, I could swear that I already tried that...
It worked.

Closing and apologies for the ticket. 🙌

**Comment by mubharaq** [comment]
@vlazdra can you please give a example of how you used this application class? Did you create a separate file for this, and where in the androidmanifest did you include this file. Thank you

**Comment by mubharaq** [comment]
@Zazo032  kindly help me out, i already have a mainActivity class

 `class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}`

How do i add the intercom initialization to this. Please note this MainActivity is already referenced in my AndroidManifest file

**Comment by Zazo032** [comment]
@moobydrey did you follow the [Android steps](https://github.com/v3rm0n/intercom_flutter/tree/master/intercom_flutter#android)? You can also find the example project here: https://github.com/v3rm0n/intercom_flutter/tree/master/intercom_flutter/example/android

**Comment by mubharaq** [comment]
Yes, i did exactyle everything on the documentation. i get the following error:

```I/FIAM.Display( 4675): Unbinding from activity: MainActivity
I/FIAM.Headless( 4675): Removing display event component
I/FIAM.Display( 4675): Binding to activity: io.intercom.android.sdk.m5.IntercomRootActivity
I/FIAM.Headless( 4675): Setting display event component
D/CompatibilityChangeReporter( 4675): Compat change id reported: 194532703; UID 10341; state: ENABLED
E/AndroidRuntime( 4675): FATAL EXCEPTION: main
E/AndroidRuntime( 4675): Process: com.example.app, PID: 4675
E/AndroidRuntime( 4675): java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'
E/AndroidRuntime( 4675): 	at kotlinx.coroutines.internal.a0.d(:81)
E/AndroidRuntime( 4675): 	at kotlinx.coroutines.internal.b0.a1(:115)
E/AndroidRuntime( 4675): 	at kotlinx.coroutines.internal.b0.V0(:96)
E/AndroidRuntime( 4675): 	at kotlinx.coroutines.internal.l.b(:319)
E/AndroidRuntime( 4675): 	at bi.a.d(:30)
E/AndroidRuntime( 4675): 	at bi.a.e(:25)
E/AndroidRuntime( 4675): 	at xh.r0.h(:110)
E/AndroidRuntime( 4675): 	at xh.a.i1(:126)
E/AndroidRuntime( 4675): 	at xh.j.c(:56)
E/AndroidRuntime( 4675): 	at xh.h.c(:1)
E/AndroidRuntime( 4675): 	at kotlinx.coroutines.flow.r.d(:209)
E/AndroidRuntime( 4675): 	at kotlinx.coroutines.flow.r.e(:147)
E/AndroidRuntime( 4675): 	at kotlinx.coroutines.flow.g.D(:1)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.home.viewmodel.HomeViewModel.<init>(:64)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.home.viewmodel.HomeViewModel.<init>(:44)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.home.viewmodel.HomeViewModel$Companion$factory$1.create(:204)
E/AndroidRuntime( 4675): 	at androidx.lifecycle.r0.b(:83)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.home.viewmodel.HomeViewModel$Companion$factory$1.create(Unknown Source:0)
E/AndroidRuntime( 4675): 	at androidx.lifecycle.q0.b(:187)
E/AndroidRuntime( 4675): 	at androidx.lifecycle.q0.a(:153)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.home.viewmodel.HomeViewModel$Companion.create(:193)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.navigation.HomeScreenDestinationKt$homeScreen$1.invoke(:40)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.navigation.HomeScreenDestinationKt$homeScreen$1.invoke(:39)
E/AndroidRuntime( 4675): 	at p0.b.b(:116)
E/AndroidRuntime( 4675): 	at p0.b.invoke(:34)
E/AndroidRuntime( 4675): 	at m3.k$c$b.invoke(:163)
E/AndroidRuntime( 4675): 	at m3.k$c$b.invoke(:162)
E/AndroidRuntime( 4675): 	at p0.b.a(:107)
E/AndroidRuntime( 4675): 	at p0.b.invoke(:34)
E/AndroidRuntime( 4675): 	at i0.t.a(:228)
E/AndroidRuntime( 4675): 	at q0.d.e(:84)
E/AndroidRuntime( 4675): 	at m3.h.b(:65)
E/AndroidRuntime( 4675): 	at m3.h.c(:1)
E/AndroidRuntime( 4675): 	at m3.h$a.invoke(:52)
E/AndroidRuntime( 4675): 	at m3.h$a.invoke(:51)
E/AndroidRuntime( 4675): 	at p0.b.a(:107)
E/AndroidRuntime( 4675): 	at p0.b.invoke(:34)
E/AndroidRuntime( 4675): 	at i0.t.a(:228)
E/AndroidRuntime( 4675): 	at m3.h.a(:47)
E/AndroidRuntime( 4675): 	at m3.k$c.invoke(:162)
E/AndroidRuntime( 4675): 	at m3.k$c.invoke(:141)
E/AndroidRuntime( 4675): 	at p0.b.b(:116)
E/AndroidRuntime( 4675): 	at p0.b.invoke(:34)
E/AndroidRuntime( 4675): 	at q.i$d.invoke(:133)
E/AndroidRuntime( 4675): 	at q.i$d.invoke(:128)
E/AndroidRuntime( 4675): 	at p0.b.a(:107)
E/AndroidRuntime( 4675): 	at p0.b.invoke(:34)
E/AndroidRuntime( 4675): 	at q.i.b(:142)
E/AndroidRuntime( 4675): 	at q.i.a(:73)
E/AndroidRuntime( 4675): 	at m3.k.b(:141)
E/AndroidRuntime( 4675): 	at m3.k.a(:67)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.IntercomRootActivity$onCreate$1$1$4.invoke(:110)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.IntercomRootActivity$onCreate$1$1$4.invoke(:104)
E/AndroidRuntime( 4675): 	at p0.b.a(:107)
E/AndroidRuntime( 4675): 	at p0.b.invoke(:34)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.IntercomStickyBottomSheetKt$IntercomStickyBottomSheet$2$4.invoke(:102)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.IntercomStickyBottomSheetKt$IntercomStickyBottomSheet$2$4.invoke(:101)
E/AndroidRuntime( 4675): 	at p0.b.a(:107)
E/AndroidRuntime( 4675): 	at p0.b.invoke(:34)
E/AndroidRuntime( 4675): 	at d0.s1$a.invoke(:134)
E/AndroidRuntime( 4675): 	at d0.s1$a.invoke(:117)
E/AndroidRuntime( 4675): 	at p0.b.a(:107)
E/AndroidRuntime( 4675): 	at p0.b.invoke(:34)
E/AndroidRuntime( 4675): 	at i0.t.a(:228)
E/AndroidRuntime( 4675): 	at d0.s1.a(:114)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.IntercomStickyBottomSheetKt$IntercomStickyBottomSheet$2.invoke(:79)
E/AndroidRuntime( 4675): 	at io.intercom.android.sdk.m5.IntercomStickyBottomSheetKt$IntercomStickyBottomSheet$2.invoke(:68)
E/AndroidRuntime( 4675): 	at p0.b.b(:116)
E/AndroidRuntime( 4675): 	at p0.b$a.invoke(:127)
E/AndroidRuntime( 4675): 	at p0.b$a.invoke(:127)
E/AndroidRuntime( 4675): 	at i0.i1.h(:145)
E/AndroidRuntime( 4675): 	at i0.l.f1(:2375)
E/AndroidRuntime( 4675): 	at i0.l.E1(:2643)
E/AndroidRuntime( 4675): 	at i0.l$i.invoke(:3260)
E/AndroidRuntime( 4675): 	at i0.l$i.invoke(:3238)
E/AndroidRuntime( 4675): 	at i0.a2.d(:341)
E/AndroidRuntime( 4675): 	at i0.z1.i(:1)
E/AndroidRuntime( 4675): 	at i0.l.v0(:3238)
E/AndroidRuntime( 4675): 	at i0.l.c1(:3203)
E/AndroidRuntime( 4675): 	at i0.q.x(:771)
E/AndroidRuntime( 4675): 	at i0.j1.f0(:1031)
E/AndroidRuntime( 4675): 	at i0.j1.K(:125)
E/AndroidRuntime( 4675): 	at i0.j1$k$a.invoke(:534)
E/AndroidRuntime( 4675): 	at i0.j1$k$a.invoke(:503)
E/AndroidRuntime( 4675): 	at androidx.compose.ui.platform.e0$c.doFrame(:34)
E/AndroidRuntime( 4675): 	at androidx.compose.ui.platform.c0.i1(:109)
E/AndroidRuntime( 4675): 	at androidx.compose.ui.platform.c0.c1(:41)
E/AndroidRuntime( 4675): 	at androidx.compose.ui.platform.c0$d.doFrame(:69)
E/AndroidRuntime( 4675): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
E/AndroidRuntime( 4675): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
E/AndroidRuntime( 4675): 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
E/AndroidRuntime( 4675): 	at android.view.Choreographer.doFrame(Choreographer.java:827)
E/AndroidRuntime( 4675): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
E/AndroidRuntime( 4675): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 4675): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4675): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 4675): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 4675): 	at android.app.ActivityThread.main(ActivityThread.java:7884)
E/AndroidRuntime( 4675): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4675): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 4675): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 4675): 	Suppressed: xh.b1: [a3{Cancelling}@3736bd5, Dispatchers.Main[missing]]
W/System  ( 4675): A resource failed to call BaseEventQueue.dispose. 
I/Process ( 4675): Sending signal. PID: 4675 SIG: 9
Lost connection to device.

**Comment by Zazo032** [comment]
Then please open a new issue with info on how to reproduce it

**Comment by vlazdra** [comment]
> @Zazo032 kindly help me out, i already have a mainActivity class
> 
> `class MainActivity: FlutterFragmentActivity() { override fun configureFlutterEngine(flutterEngine: FlutterEngine) { GeneratedPluginRegistrant.registerWith(flutterEngine) } }`
> 
> How do i add the intercom initialization to this. Please note this MainActivity is already referenced in my AndroidManifest file

You need to add the initialization steps to the Application class, not the Activity. Follow the steps for adding the Application class init.

**Comment by mubharaq** [comment]
> > @Zazo032 kindly help me out, i already have a mainActivity class
> > `class MainActivity: FlutterFragmentActivity() { override fun configureFlutterEngine(flutterEngine: FlutterEngine) { GeneratedPluginRegistrant.registerWith(flutterEngine) } }`
> > How do i add the intercom initialization to this. Please note this MainActivity is already referenced in my AndroidManifest file
> 
> You need to add the initialization steps to the Application class, not the Activity. Follow the steps for adding the Application class init.

This is my application class

```package com.myapp.app

import android.app.Application
import io.maido.intercom.IntercomFlutterPlugin

class MyApp : Application() {
    override fun onCreate() {
        super.onCreate()

        // Add this line with your keys
        IntercomFlutterPlugin.initSdk(this, appId = "intercomId", androidApiKey = "androidKey")
    }
}
```

**Comment by vlazdra** [comment]
> > > @Zazo032 kindly help me out, i already have a mainActivity class
> > > `class MainActivity: FlutterFragmentActivity() { override fun configureFlutterEngine(flutterEngine: FlutterEngine) { GeneratedPluginRegistrant.registerWith(flutterEngine) } }`
> > > How do i add the intercom initialization to this. Please note this MainActivity is already referenced in my AndroidManifest file
> > 
> > 
> > You need to add the initialization steps to the Application class, not the Activity. Follow the steps for adding the Application class init.
> 
> This is my application class
> 
> ```
> 
> import android.app.Application
> import io.maido.intercom.IntercomFlutterPlugin
> 
> class MyApp : Application() {
>     override fun onCreate() {
>         super.onCreate()
> 
>         // Add this line with your keys
>         IntercomFlutterPlugin.initSdk(this, appId = "intercomId", androidApiKey = "androidKey")
>     }
> }
> ```

And as @Zazo032 mentioned, you really need to follow the steps provided inside the Readme.
Also, there is almost always an example that demonstrates how to use a feature/implementation.

In your case, you need to add your Application class (MyApp) to the AndroidManifest.xml as shown in the example project here: https://github.com/v3rm0n/intercom_flutter/blob/master/intercom_flutter/example/android/app/src/main/AndroidManifest.xml

**Comment by mubharaq** [comment]
> > > > @Zazo032 kindly help me out, i already have a mainActivity class
> > > > `class MainActivity: FlutterFragmentActivity() { override fun configureFlutterEngine(flutterEngine: FlutterEngine) { GeneratedPluginRegistrant.registerWith(flutterEngine) } }`
> > > > How do i add the intercom initialization to this. Please note this MainActivity is already referenced in my AndroidManifest file
> > > 
> > > 
> > > You need to add the initialization steps to the Application class, not the Activity. Follow the steps for adding the Application class init.
> > 
> > 
> > This is my application class
> > ```
> > 
> > import android.app.Application
> > import io.maido.intercom.IntercomFlutterPlugin
> > 
> > class MyApp : Application() {
> >     override fun onCreate() {
> >         super.onCreate()
> > 
> >         // Add this line with your keys
> >         IntercomFlutterPlugin.initSdk(this, appId = "intercomId", androidApiKey = "androidKey")
> >     }
> > }
> > ```
> 
> And as @Zazo032 mentioned, you really need to follow the steps provided inside the Readme. Also, there is almost always an example that demonstrates how to use a feature/implementation.
> 
> In your case, you need to add your Application class (MyApp) to the AndroidManifest.xml as shown in the example project here: https://github.com/v3rm0n/intercom_flutter/blob/master/intercom_flutter/example/android/app/src/main/AndroidManifest.xml

Here is my manifest

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.myapp.app">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.CAMERA"/>

   <application
        android:label="Example App"
        android:name=".MyApp"
        android:icon="@mipmap/ic_launcher">
       <meta-data
           android:name="com.google.firebase.messaging.default_notification_icon"
           android:resource="@drawable/ic_stat_name" />
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

The problem for me is that the app crashes on android when i try to open the intercom messenger

**Comment by vlazdra** [comment]
@moobydrey Alright. Then follow what @Zazo032 said, open another issue where you can provide all the details. This issue is not relevant to what you are experiencing.
