### ISSUE TITLE
Android App Crashes When Open Intercom: IllegalStateException

### ISSUE THREAD

**Issue by Nahrawene-ben-hmida** [deepak786/intercom_flutter#345]
Title: Android App Crashes When Open Intercom: IllegalStateException

## Issue Description:
On Android, attempting to open Intercom results in an application crash with the following error: `IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.`

## Environment:
- Flutter version: 3.10.6 
- Intercom for Flutter version: 7.8.3
- Gradle version:  gradle-7.1.3
- kotlin version = '1.7.20'

## To Reproduce:
call : Intercom.instance.displayMessenger()

## Expected Result:
should open intercom view 

## Actual Result:
When the Intercom is clicked, the app crashes and throws the error: `IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.`

 ## Logs:
D/AndroidRuntime(18907): Shutting down VM
E/AndroidRuntime(18907): FATAL EXCEPTION: main
E/AndroidRuntime(18907): Process: com.expensya.revamped, PID: 18907
E/AndroidRuntime(18907): java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
E/AndroidRuntime(18907): 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5235)
E/AndroidRuntime(18907): 	at android.view.ViewGroup.addView(ViewGroup.java:5064)
E/AndroidRuntime(18907): 	at android.view.ViewGroup.addView(ViewGroup.java:5004)
E/AndroidRuntime(18907): 	at android.view.ViewGroup.addView(ViewGroup.java:4976)
E/AndroidRuntime(18907): 	at app.screeb.sdk.ScreebWebView.onActivityStarted(SourceFile:2)
E/AndroidRuntime(18907): 	at android.app.Application.dispatchActivityStarted(Application.java:406)
E/AndroidRuntime(18907): 	at android.app.Activity.dispatchActivityStarted(Activity.java:1348)
E/AndroidRuntime(18907): 	at android.app.Activity.onStart(Activity.java:1833)
E/AndroidRuntime(18907): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
E/AndroidRuntime(18907): 	at android.app.Activity.performStart(Activity.java:8024)
E/AndroidRuntime(18907): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
E/AndroidRuntime(18907): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
E/AndroidRuntime(18907): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
E/AndroidRuntime(18907): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
E/AndroidRuntime(18907): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(18907): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(18907): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(18907): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(18907): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(18907): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18907): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(18907): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (18907): Sending signal. PID: 18907 SIG: 9

## Screenshots: 
[
![image](https://github.com/v3rm0n/intercom_flutter/assets/65221209/c22b8b3f-c9bd-4057-b487-12d727d3b735)
](url)
![image](https://github.com/v3rm0n/intercom_flutter/assets/65221209/82f61511-3ec8-4d25-88dc-46ab9978b0fc)

I would appreciate any help in resolving this issue. Thanks!

**Comment by khalilyamoun** [comment]
We're currently facing the same issue :(
It's blocking for the majority of our clients.

**Comment by deepak786** [comment]
Can you test the [example app ](https://github.com/v3rm0n/intercom_flutter/tree/master/intercom_flutter/example) and see if it is also crashing?
Also try the latest `intercom_flutter: 7.8.4`

**Comment by deepak-agendaboa** [comment]
I'm checking this issue with Intercom support team.

Meanwhile @Nahrawene-ben-hmida @khalilyamoun Is there any update related to my last comment?

**Comment by deepak786** [comment]
I'm checking this issue with Intercom support team.

Meanwhile @Nahrawene-ben-hmida @khalilyamoun Is there any update related to my last comment?

**Comment by abed-supy-io** [comment]
any updates ?

**Comment by binSaed** [comment]
@deepak786 
any update 
```
       Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5601)
       at android.view.ViewGroup.addView(ViewGroup.java:5387)
       at android.view.ViewGroup.addView(ViewGroup.java:5327)
       at android.view.ViewGroup.addView(ViewGroup.java:5299)
       at androidx.compose.ui.viewinterop.AndroidViewHolder.<init>(AndroidViewHolder.android.kt:112)
       at androidx.compose.ui.viewinterop.ViewFactoryHolder.<init>(AndroidView.android.kt:317)
       at androidx.compose.ui.viewinterop.ViewFactoryHolder.<init>(AndroidView.android.kt:307)
       at androidx.compose.ui.viewinterop.ViewFactoryHolder.<init>(AndroidView.android.kt:327)
       at androidx.compose.ui.viewinterop.AndroidView_androidKt$createAndroidViewNodeFactory$1$1.invoke(AndroidView.android.kt:261)
       at androidx.compose.ui.viewinterop.AndroidView_androidKt$createAndroidViewNodeFactory$1$1.invoke(AndroidView.android.kt:260)
       at androidx.compose.runtime.changelist.Operation$InsertNodeFixup.execute(Operation.kt:705)
       at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:349)
       at androidx.compose.runtime.changelist.FixupList.executeAndFlushAllPendingFixups(FixupList.kt:53)
       at androidx.compose.runtime.changelist.Operation$InsertSlotsWithFixups.execute(Operation.kt:665)
       at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:349)
       at androidx.compose.runtime.changelist.ChangeList.executeAndFlushAllPendingChanges(ChangeList.kt:88)
       at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:1036)
       at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1067)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:684)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:591)
       at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:39)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:108)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:2327)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:2338)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1498)
       at android.view.Choreographer.doFrame(Choreographer.java:1324)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:2248)
       at android.os.Handler.handleCallback(Handler.java:997)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loopOnce(Looper.java:237)
       at android.os.Looper.loop(Looper.java:325)
       at android.app.ActivityThread.main(ActivityThread.java:10378)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:635)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:961)
        
```


<img width="1539" height="956" alt="Image" src="https://github.com/user-attachments/assets/307c201d-b829-455f-861a-4041ba60d460" />

**Comment by deepak786** [comment]
I believe it was resolved in `intercom_flutter: 9.4.1`

https://github.com/intercom/intercom-android/releases/tag/17.0.1
