### ISSUE TITLE
Fatal Exception: java.net.MalformedURLException

### ISSUE THREAD

**Issue by JustineUgo** [deepak786/intercom_flutter#480]
After integrating intercom_flutter 9.1.1 into my app and releasing to my users, Firebase crashlytics reported 3 events of the same error with these logs.

```
Fatal Exception: java.net.MalformedURLException: no protocol: 
       at java.net.URL.<init>(URL.java:601)
       at java.net.URL.<init>(URL.java:498)
       at java.net.URL.<init>(URL.java:447)
       at io.intercom.android.sdk.ui.preview.viewmodel.PreviewViewModel.prepareBitmap(PreviewViewModel.kt:275)
       at io.intercom.android.sdk.ui.preview.viewmodel.PreviewViewModel.access$get_state$p(PreviewViewModel.kt)
       at io.intercom.android.sdk.ui.preview.viewmodel.PreviewViewModel.access$prepareBitmap(PreviewViewModel.kt)
       at io.intercom.android.sdk.ui.preview.viewmodel.PreviewViewModel$saveImage$1.invokeSuspend(PreviewViewModel.kt:89)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt)
       
```

I havent found any solution or explanation to it.

**Comment by deepak786** [comment]
Seems that it is fixed in Intercom Android SDK version 15.11.1 https://github.com/intercom/intercom-android/blob/master/CHANGELOG.md#15111

**Comment by JustineUgo** [comment]
@deepak786 would there be a new intercom_flutter version with the fix?

**Comment by deepak786** [comment]
Yes

**Comment by JustineUgo** [comment]
@deepak786 
I ran into this issue after upgrading to `intercom_flutter: ^9.2.0`

```

Error: The pod "Intercom" required by the plugin "intercom_flutter" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "intercom_flutter", or contact the plugin's developers for assistance.
Error running pod install
```

**Comment by deepak786** [comment]
What is `platform :ios` version in your podfile?

**Comment by deepak786** [comment]
or try this
```
pod install --repo-update
```

**Comment by JustineUgo** [comment]
> What is `platform :ios` version in your podfile?

its `platform :ios, '15.0'`

**Comment by JustineUgo** [comment]
> or try this
> 
> ```
> pod install --repo-update
> ```

Thanks, this worked fine.
