### ISSUE TITLE
Flutter Intercom package gives an IllegalArgumentException: Unknown color, app crashes

### ISSUE THREAD

**Issue by sebastiaands** [deepak786/intercom_flutter#66]
Since recently our Flutter app crashes directly on startup. Given the stack trace, it looks like something goes wrong with the Intercom SDK we are using.

I was using version 2.0.4, but upgrading to the latest version 2.1.1 doesn't help. When I use a different Intercom App ID, the problem seems to be gone. So it might have something to do with the configuration of our workspace.

The stack trace:

```
E/AndroidRuntime(27597): java.lang.IllegalArgumentException: Unknown color
E/AndroidRuntime(27597): 	at android.graphics.Color.parseColor(Color.java:1391)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.identity.AppConfig.getConfigColor(AppConfig.java:233)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.identity.AppConfig.update(AppConfig.java:187)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.middleware.AppConfigMiddleware.dispatch(AppConfigMiddleware.java:29)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.middleware.UserIdentityMiddleware.dispatch(UserIdentityMiddleware.java:19)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.middleware.FirstMessageMiddleware.dispatch(FirstMessageMiddleware.java:29)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.middleware.AudioMiddleware.dispatch(AudioMiddleware.java:32)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.middleware.OverlayPresenterMiddleware.dispatch(OverlayPresenterMiddleware.java:61)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.middleware.NexusClientMiddleware.dispatch(NexusClientMiddleware.java:30)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.middleware.UserUpdateBatcherMiddleware.dispatch(UserUpdateBatcherMiddleware.java:28)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.middleware.ApiMiddleware.dispatch(ApiMiddleware.java:20)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.middleware.LoggerMiddleware.dispatch(LoggerMiddleware.java:20)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.store.Store.dispatch(Store.java:81)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.api.CallbackHolder$1.onSuccess(CallbackHolder.java:46)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.api.CallbackHolder$1.onSuccess(CallbackHolder.java:43)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.api.Api$1.onSuccess(Api.java:177)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.api.Api$1.onSuccess(Api.java:173)
E/AndroidRuntime(27597): 	at io.intercom.android.sdk.api.BaseCallback.onResponse(BaseCallback.java:32)
E/AndroidRuntime(27597): 	at io.intercom.retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
E/AndroidRuntime(27597): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(27597): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(27597): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(27597): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(27597): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27597): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(27597): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by Zazo032** [comment]
This seems to be an issue with Android's Intercom SDK library, try to report it to Intercom directly, as this plugin is only a wrapper for native methods

**Comment by Spikes042** [comment]
You can set up Intercom UI theme colour from the web platform, so I'm assuming the SDK pulls this config. Make sure that the value there is correct.

You can find it on this page: `https://app.intercom.com/a/apps/{your_app_id}/messenger`
Under **Style your Messenger**

**Comment by ymcewen** [comment]
@sebastiaands did you get anywhere with this?

I’m having the same issue using React Native. For the life of me I can’t figure out what is wrong as when I try a different workspace, everything works fine.

**Comment by Zazo032** [comment]
Did you try contacting Intercom? This seems to be an Intercom related issue, but not with this plugin

**Comment by sebastiaands** [comment]
Hi @ymcewen, @Zazo032, somewhere in your workspace you can set the `helpCenterBaseColor`. If that value is not parsable by the SDK, it crashes. I've contacted Intercom, they said they are passing it to the development team. So I think this issue can be closed here.

**Comment by ymcewen** [comment]
Thanks so much!!!
