### ISSUE TITLE
[Android] Crash when calling displayMessanger()

### ISSUE THREAD

**Issue by mazo20** [deepak786/intercom_flutter#76]
The whole app crashes when Intercom.displayMessanger() or Intercom.displayMessageComposer() is called.
It's similar to #47 but not exactly. It noticed it first in 2.0.7 and still happens in 2.2.0

```
E/AndroidRuntime(14996): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/LifecycleEventObserver;
E/AndroidRuntime(14996): 	at io.intercom.android.sdk.activities.IntercomMessengerActivity.openHomeScreen(IntercomMessengerActivity.java:342)
E/AndroidRuntime(14996): 	at io.intercom.android.sdk.overlay.LauncherOpenBehaviour.presentHome(LauncherOpenBehaviour.java:85)
E/AndroidRuntime(14996): 	at io.intercom.android.sdk.overlay.LauncherOpenBehaviour.openLastOrDefaultState(LauncherOpenBehaviour.java:67)
E/AndroidRuntime(14996): 	at io.intercom.android.sdk.overlay.LauncherOpenBehaviour.openMessenger(LauncherOpenBehaviour.java:47)
E/AndroidRuntime(14996): 	at io.intercom.android.sdk.RealIntercom.displayMessenger(RealIntercom.java:286)
E/AndroidRuntime(14996): 	at io.maido.intercom.IntercomFlutterPlugin.onMethodCall(IntercomFlutterPlugin.kt:82)
E/AndroidRuntime(14996): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/AndroidRuntime(14996): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(14996): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/AndroidRuntime(14996): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(14996): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime(14996): 	at android.os.Looper.loop(Looper.java:174)
E/AndroidRuntime(14996): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(14996): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14996): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(14996): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(14996): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.LifecycleEventObserver" on path: DexPathList[[zip file "/data/app/com.moneymatix.app-qxs-VUAySpv86-pdr25l8g==/base.apk"],nativeLibraryDirectories=[/data/app/com.moneymatix.app-qxs-VUAySpv86-pdr25l8g==/lib/x86, /data/app/com.moneymatix.app-qxs-VUAySpv86-pdr25l8g==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
E/AndroidRuntime(14996): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime(14996): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(14996): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(14996): 	... 16 more
I/Process (14996): Sending signal. PID: 14996 SIG: 9
Lost connection to device.
```

This is from a simulator but it happens on real devices as well.

**Comment by mazo20** [comment]
For anyone having that issue, after hours and hours of debugging it turns out that it was a different plugin, catcher 0.2.7 that was causing the problem in Intercom. After deleting catcher, everything works fine now.

There might be still something to be fixed here, I'm not sure why a plugin can interfere with a different one.

**Comment by ningo-agilityio** [comment]
I'm facing the @mazo20 
Even I removed catcher, it still doesn't work.

**Comment by deepak786** [comment]
@mazo20 @ningo-agilityio do you guys still have the issue with the latest intercom_flutter?

**Comment by karimafas** [comment]
I experienced the same issue as the OP when I implemented what I thought was a fix to the following error:
`Duplicate class androidx.lifecycle.ViewModelLazy found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.5.1-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.1)`

My initial response was to exclude the androidx.lifecycle group all together from app/build.gradle like this:
``` 
configurations {
   all {
         exclude group: 'androidx.lifecycle', module: 'lifecycle-runtime-ktx'
         exclude group: 'androidx.lifecycle', module: 'lifecycle-viewmodel-ktx'
   } 
}
```

However on second look, the compiler is warning it has found two different versions of androidx.lifecycle, so what worked was forcing the implementation of version 2.5.1 in app/build.gradle by doing the following:
``` 
def lifecycle_version = "2.5.1"
dependencies {
      implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
      implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
}
```

I did not have catcher installed, but this is probably due to the fact I am implementing intercom_flutter 5.3.0.
